### Obtener todos los usuarios
GET http://localhost:5000/a/usuarios HTTP/1.1

### Registrar nuevo usuario
POST http://localhost:5000/a/usuarios/register HTTP/1.1
Content-Type: application/json

{
    "email": "usuadsdassej@gmail.com",
    "password": "123456",
    "name": "usuario ej",
    "country": "Perú"
}

### Iniciar sesión
POST http://localhost:5000/a/usuarios/login HTTP/1.1
Content-Type: application/json

{
    "email": "usuarioej@gmail.com",
    "password": "123456"
}

### Actualizar usuario (ID = 1)
PUT http://localhost:5000/a/usuarios/1 HTTP/1.1
Content-Type: application/json

{
    "email": "usuarioej2@gmail.com",
    "password": "12345678",
    "name": "usuario ej actualizado",
    "country": "Perú",
    "role": "admin"
}