SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

INSERT INTO public."Juego" VALUES ('GTA_V', 'Un juego de acción y aventura de mundo abierto, donde puedes explorar una ciudad ficticia, cometer crímenes y vivir aventuras con diferentes personajes.', '{/images/games/gta_v_1.jpg,/images/games/gta_v_2.jpg,/images/games/gta_v_3.jpg,/images/games/gta_v_4.jpg}', 'Grand Theft Auto V', 'https://www.youtube.com/embed/nzV5_Uhu08A', 199, 20, '17/09/2013');
INSERT INTO public."Juego" VALUES ('NFS_Heat', 'Un juego de carreras lleno de acción y adrenalina, con la posibilidad de personalizar vehículos y competir en circuitos nocturnos.', '{/images/games/nfs_heat_1.jpg,/images/games/nfs_heat_2.jpg,/images/games/nfs_heat_3.jpg,/images/games/nfs_heat_4.jpg}', 'Need for Speed Heat', 'https://www.youtube.com/embed/9ewiJJe_nYI', 199, 15, '08/11/2019');
INSERT INTO public."Juego" VALUES ('Cyberpunk_2077', 'Un juego de rol y acción ambientado en un futuro distópico, donde tomas el rol de un mercenario en la ciudad de Night City.', '{/images/games/cyberpunk_2077_1.jpg,/images/games/cyberpunk_2077_2.jpg,/images/games/cyberpunk_2077_3.jpg,/images/games/cyberpunk_2077_4.jpg}', 'Cyberpunk 2077', 'https://www.youtube.com/embed/nLhWWoAaZ0Q', 153, 25, '10/12/2020');
INSERT INTO public."Juego" VALUES ('Red_Dead_Redemption 2', 'Un juego de acción y aventura ambientado en el Viejo Oeste, donde los jugadores toman el rol de un forajido que explora un mundo abierto y toma decisiones clave.', '{/images/games/rdr2_1.jpg,/images/games/rdr2_2.jpg,/images/games/rdr2_3.jpg,/images/games/rdr2_4.jpg}', 'Red Dead Redemption 2', 'https://www.youtube.com/embed/eaW0tYpxyp0', 153, 30, '26/10/2018');
INSERT INTO public."Juego" VALUES ('Horizon_Forbidden_West', 'Un juego de aventura y acción en un mundo post-apocalíptico, donde controlas a Aloy, una cazadora que combate máquinas en un entorno vasto y diverso.', '{/images/games/horizon_forbidden_west_1.jpg,/images/games/horizon_forbidden_west_2.jpg,/images/games/horizon_forbidden_west_3.jpg,/images/games/horizon_forbidden_west_4.jpg}', 'Horizon Forbidden West', 'https://www.youtube.com/embed/Lq594XmpPBg', 197, 15, '18/02/2022');
INSERT INTO public."Juego" VALUES ('Ghost_of_Tsushima', 'Un juego de acción y aventura ambientado en el Japón feudal, donde tomas el rol de un samurái que lucha por defender su hogar.', '{/images/games/ghost_of_tsushima_1.jpg,/images/games/ghost_of_tsushima_2.jpg,/images/games/ghost_of_tsushima_3.jpg,/images/games/ghost_of_tsushima_4.jpg}', 'Ghost of Tsushima', 'https://www.youtube.com/embed/iqysmS4lxwQ', 199, 20, '17/07/2020');
INSERT INTO public."Juego" VALUES ('Assassins_Creed_Valhalla', 'Un juego de acción y aventura ambientado en la época vikinga, donde controlas a un guerrero vikingo mientras exploras un mundo abierto y realizas misiones.', '{/images/games/assassins_creed_valhalla_1.jpg,/images/games/assassins_creed_valhalla_2.jpg,/images/games/assassins_creed_valhalla_3.jpg,/images/games/assassins_creed_valhalla_4.jpg}', 'Assassin’s Creed Valhalla', 'https://www.youtube.com/embed/ssrNcwxALS4', 197, 10, '10/11/2020');
INSERT INTO public."Juego" VALUES ('Spider-Man', 'Un juego de acción y aventura basado en el famoso superhéroe Spider-Man, donde puedes balancearte por la ciudad de Nueva York y luchar contra diversos villanos.', '{/images/games/spiderman_1.jpg,/images/games/spiderman_2.jpg,/images/games/spiderman_3.jpg,/images/games/spiderman_4.jpg}', 'Marvel’s Spider-Man Remastered', 'https://www.youtube.com/embed/1E051WtpyWg', 180, 15, '12/08/2020');
INSERT INTO public."Juego" VALUES ('Resident_Evil_4_Remake', 'Un juego de survival horror donde controlas a Leon S. Kennedy en una misión para rescatar a la hija del presidente mientras lucha contra criaturas infectadas.', '{/images/games/resident_evil_4_remake_1.jpg,/images/games/resident_evil_4_remake_2.jpg,/images/games/resident_evil_4_remake_3.jpg,/images/games/resident_evil_4_remake_4.jpg}', 'Resident Evil 4 Remake', 'https://www.youtube.com/embed/j5Ic2z3_xp0', 153, 0, '24/03/2023');
INSERT INTO public."Juego" VALUES ('Elden_Ring', 'Un juego de rol de acción en un mundo abierto donde los jugadores exploran un vasto mundo, luchan contra jefes desafiantes y mejoran sus habilidades.', '{/images/games/elden_ring_1.jpg,/images/games/elden_ring_2.jpg,/images/games/elden_ring_3.jpg,/images/games/elden_ring_4.jpg}', 'Elden Ring', 'https://www.youtube.com/embed/AKXiKBnzpBQ', 172, 10, '25/02/2022');

INSERT INTO public."Calificacion" VALUES (1, 'GTA_V', 'Una experiencia increíble, la mejor entrega de la saga GTA.', 5, 'John Doe');
INSERT INTO public."Calificacion" VALUES (2, 'GTA_V', 'Excelente juego, pero los controles pueden ser mejorados.', 4, 'Jane Smith');
INSERT INTO public."Calificacion" VALUES (3, 'NFS_Heat', 'Muy entretenido, la personalización de los autos es impresionante.', 4, 'Carlos Ruiz');
INSERT INTO public."Calificacion" VALUES (4, 'NFS_Heat', 'Un juego muy divertido, aunque a veces se vuelve repetitivo.', 3, 'Laura González');
INSERT INTO public."Calificacion" VALUES (6, 'Elden_Ring', 'Una obra maestra, uno de los mejores juegos de rol de todos los tiempos.', 5, 'Alex Martínez');
INSERT INTO public."Calificacion" VALUES (7, 'Elden_Ring', 'Increíblemente desafiante y hermoso. La dificultad es extrema.', 5, 'Marta López');
INSERT INTO public."Calificacion" VALUES (8, 'Cyberpunk_2077', 'A pesar de los problemas iniciales, ahora es un juego impresionante.', 4, 'Pedro Hernández');
INSERT INTO public."Calificacion" VALUES (9, 'Cyberpunk_2077', 'Excelente historia, pero la jugabilidad aún necesita mejoras.', 4, 'Sofia Ramírez');
INSERT INTO public."Calificacion" VALUES (10, 'Red_Dead_Redemption 2', 'Una experiencia única, una de las mejores historias de la historia de los videojuegos.', 5, 'Carlos Pérez');
INSERT INTO public."Calificacion" VALUES (11, 'Red_Dead_Redemption 2', 'El mundo abierto es impresionante, pero la historia se siente un poco larga.', 4, 'Ricardo Jiménez');
INSERT INTO public."Calificacion" VALUES (12, 'Horizon_Forbidden_West', 'Impresionante mundo, la jugabilidad es fantástica y la historia te engancha.', 5, 'Luis Rodríguez');
INSERT INTO public."Calificacion" VALUES (13, 'Horizon_Forbidden_West', 'Muy buen juego, pero se siente algo repetitivo en ciertos momentos.', 4, 'Luis Rodríguez');
INSERT INTO public."Calificacion" VALUES (14, 'Ghost_of_Tsushima', 'Un juego visualmente impresionante, y la historia es muy emocional.', 5, 'Juan Carlos');
INSERT INTO public."Calificacion" VALUES (15, 'Ghost_of_Tsushima', 'Gran historia y ambientación, pero algunas mecánicas de combate son repetitivas.', 4, 'Rosa Díaz');
INSERT INTO public."Calificacion" VALUES (16, 'Assassins_Creed_Valhalla', 'Una de las mejores entregas de la saga, con un mundo vasto y lleno de detalles.', 5, 'Oscar Méndez');
INSERT INTO public."Calificacion" VALUES (17, 'Assassins_Creed_Valhalla', 'Muy divertido, aunque algunas mecánicas se sienten un poco forzadas.', 4, 'Beatriz García');
INSERT INTO public."Calificacion" VALUES (18, 'Spider-Man', '¡Es como ser Spider-Man! La jugabilidad es increíble y la historia muy entretenida.', 5, 'Antonio Pérez');
INSERT INTO public."Calificacion" VALUES (19, 'Spider-Man', 'Un juego divertido, pero algunos villanos no están bien desarrollados.', 4, 'Carmen Ruiz');
INSERT INTO public."Calificacion" VALUES (20, 'Resident_Evil_4_Remake', 'La mejor remasterización de la saga, un clásico modernizado.', 5, 'Francisco Álvarez');
INSERT INTO public."Calificacion" VALUES (21, 'Resident_Evil_4_Remake', 'Es un gran remake, pero algunas partes pierden el toque clásico del original.', 4, 'Patricia Gómez');

INSERT INTO public."Categoria" VALUES (1, 'Acción');
INSERT INTO public."Categoria" VALUES (2, 'Aventura');
INSERT INTO public."Categoria" VALUES (3, 'Multijugador');
INSERT INTO public."Categoria" VALUES (4, 'Más vendido');
INSERT INTO public."Categoria" VALUES (5, 'Mejor valorado');
INSERT INTO public."Categoria" VALUES (6, 'Carreras');
INSERT INTO public."Categoria" VALUES (7, 'RPG');
INSERT INTO public."Categoria" VALUES (8, 'Survival Horror');

INSERT INTO public."CategoriaJuego" VALUES ('GTA_V', 1);
INSERT INTO public."CategoriaJuego" VALUES ('GTA_V', 2);
INSERT INTO public."CategoriaJuego" VALUES ('GTA_V', 3);
INSERT INTO public."CategoriaJuego" VALUES ('GTA_V', 4);
INSERT INTO public."CategoriaJuego" VALUES ('GTA_V', 5);
INSERT INTO public."CategoriaJuego" VALUES ('NFS_Heat', 3);
INSERT INTO public."CategoriaJuego" VALUES ('NFS_Heat', 6);
INSERT INTO public."CategoriaJuego" VALUES ('Elden_Ring', 7);
INSERT INTO public."CategoriaJuego" VALUES ('Elden_Ring', 1);
INSERT INTO public."CategoriaJuego" VALUES ('Elden_Ring', 5);
INSERT INTO public."CategoriaJuego" VALUES ('Cyberpunk_2077', 7);
INSERT INTO public."CategoriaJuego" VALUES ('Cyberpunk_2077', 1);
INSERT INTO public."CategoriaJuego" VALUES ('Cyberpunk_2077', 2);
INSERT INTO public."CategoriaJuego" VALUES ('Cyberpunk_2077', 4);
INSERT INTO public."CategoriaJuego" VALUES ('Red_Dead_Redemption 2', 1);
INSERT INTO public."CategoriaJuego" VALUES ('Red_Dead_Redemption 2', 2);
INSERT INTO public."CategoriaJuego" VALUES ('Red_Dead_Redemption 2', 5);
INSERT INTO public."CategoriaJuego" VALUES ('Horizon_Forbidden_West', 1);
INSERT INTO public."CategoriaJuego" VALUES ('Horizon_Forbidden_West', 2);
INSERT INTO public."CategoriaJuego" VALUES ('Horizon_Forbidden_West', 4);
INSERT INTO public."CategoriaJuego" VALUES ('Ghost_of_Tsushima', 1);
INSERT INTO public."CategoriaJuego" VALUES ('Ghost_of_Tsushima', 2);
INSERT INTO public."CategoriaJuego" VALUES ('Ghost_of_Tsushima', 5);
INSERT INTO public."CategoriaJuego" VALUES ('Assassins_Creed_Valhalla', 1);
INSERT INTO public."CategoriaJuego" VALUES ('Assassins_Creed_Valhalla', 2);
INSERT INTO public."CategoriaJuego" VALUES ('Assassins_Creed_Valhalla', 3);
INSERT INTO public."CategoriaJuego" VALUES ('Spider-Man', 1);
INSERT INTO public."CategoriaJuego" VALUES ('Spider-Man', 2);
INSERT INTO public."CategoriaJuego" VALUES ('Spider-Man', 5);
INSERT INTO public."CategoriaJuego" VALUES ('Resident_Evil_4_Remake', 1);
INSERT INTO public."CategoriaJuego" VALUES ('Resident_Evil_4_Remake', 5);
INSERT INTO public."CategoriaJuego" VALUES ('Resident_Evil_4_Remake', 8);

INSERT INTO public."Noticia" VALUES (4, 'Final Fantasy por fin deja exclusividad con PlayStation en consolas', 'PlanetGame', 'Estrategia', 30, 'https://i0.wp.com/levelup.buscafs.com/2025/06/Final-Fantasy-VII-Remake-Intergade-Final-Fantasy-XVI-port-Xbox-Square-Enix-Xbox-Games-Showcase.jpg?resize=320,144&quality=75&strip=all', 'Microsoft reafirmó todas las mejoras que tendrá esta versión, tanto en single player como multijugador');
INSERT INTO public."Noticia" VALUES (3, 'Tu aventura en Indiana Jones and the Great Circle continuará con The Order of Giants', 'Sony', 'Aventura', 18, 'https://i0.wp.com/levelup.buscafs.com/2025/06/Indiana-528e009bdea8ecc04fc3-1536x864-1-401b99a11368a1b0820c.jpg?resize=320,144&quality=75&strip=all', 'El contenido adicional debutará de forma simultánea en todas las plataformas');
INSERT INTO public."Noticia" VALUES (2, 'Xbox canceló el estreno de Gears of War: Reloaded', 'Equipo GameStore', 'Shooter', 26, 'https://i0.wp.com/levelup.buscafs.com/2025/06/Cancelan-Gears-para-PS5-en-Japont.jpg?resize=320,144&quality=75&strip=all', 'La compañía ofreció disculpas a los usuarios de la consola de Sony que serán afectados');
INSERT INTO public."Noticia" VALUES (1, 'Nintendo Switch 2: la mejor consola', 'Nintendo', 'Actualidad', 10, 'https://i0.wp.com/levelup.buscafs.com/2025/06/Switch-2-3.jpg?resize=320,144&quality=75&strip=all', 'Se espera que los propietarios de la nueva consola de la compañía japonesa puedan ver videos en YouTube');

INSERT INTO public."Plataforma" VALUES (1, 'PlayStation');
INSERT INTO public."Plataforma" VALUES (2, 'Xbox');
INSERT INTO public."Plataforma" VALUES (3, 'Windows');

INSERT INTO public."PlataformaJuego" VALUES ('GTA_V', 1);
INSERT INTO public."PlataformaJuego" VALUES ('GTA_V', 2);
INSERT INTO public."PlataformaJuego" VALUES ('GTA_V', 3);
INSERT INTO public."PlataformaJuego" VALUES ('NFS_Heat', 1);
INSERT INTO public."PlataformaJuego" VALUES ('NFS_Heat', 2);
INSERT INTO public."PlataformaJuego" VALUES ('NFS_Heat', 3);
INSERT INTO public."PlataformaJuego" VALUES ('Elden_Ring', 1);
INSERT INTO public."PlataformaJuego" VALUES ('Elden_Ring', 2);
INSERT INTO public."PlataformaJuego" VALUES ('Elden_Ring', 3);
INSERT INTO public."PlataformaJuego" VALUES ('Cyberpunk_2077', 1);
INSERT INTO public."PlataformaJuego" VALUES ('Cyberpunk_2077', 2);
INSERT INTO public."PlataformaJuego" VALUES ('Cyberpunk_2077', 3);
INSERT INTO public."PlataformaJuego" VALUES ('Resident_Evil_4_Remake', 3);

SELECT pg_catalog.setval('public."Calificacion_id_seq"', 21, true);
SELECT pg_catalog.setval('public."Categoria_id_seq"', 40, true);
SELECT pg_catalog.setval('public."Plataforma_id_seq"', 3, true);
